#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Jan 30, 2021 08:56:24 PM EET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import dowfile_support
from tkinter import StringVar


def vp_start_gui():
    """Starting point when module is the main routine."""
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    dowfile_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(rt, *args, **kwargs):
    """Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' ."""
    global w, w_win, root
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    dowfile_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
           top is the toplevel containing window."""
        _bgcolor = "#d9d9d9"  # X11 color: 'gray85'
        _fgcolor = "#000000"  # X11 color: 'black'
        _compcolor = "#d9d9d9"  # X11 color: 'gray85'
        _ana1color = "#d9d9d9"  # X11 color: 'gray85'
        _ana2color = "#ececec"  # Closest X11 color: 'gray92'

        top.geometry("574x148+369+103")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("Dowload File")
        top.configure(background="#808080")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.314, rely=0.068, height=21, width=224)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text="""Введите ссылку на файл""")

        self.text1 = StringVar()
        spam = root.clipboard_get()
        self.text1.set(spam)
        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.052, rely=0.27, height=20, relwidth=0.895)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")
        self.Entry1.configure(validate="focus")
        self.Entry1.configure(textvariable=self.text1)

        self.textButton1 = StringVar()
        self.textButton1.set("Скачать")
        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.418, rely=0.743, height=24, width=97)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(textvariable=self.textButton1)
        self.Button1.configure(command=self.Dowload)

        self.text2 = StringVar()
        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.052, rely=0.473, height=20, relwidth=0.617)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="blue")
        self.Entry2.configure(selectforeground="white")
        self.Entry2.configure(textvariable=self.text2)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=-0.714, rely=0.676, height=21, width=134)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text="""файл""")

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.767, rely=0.473, height=24, width=107)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text="""Сохранить файл""")
        self.Button2.configure(command=self.choose_directory)

    def choose_directory(self):
        import tkinter.filedialog as fd

        directory = fd.askdirectory(title="Открыть папку", initialdir="/")
        if directory:
            print(directory)
            self.text2.set(directory)

    def Dowload(self):
        import requests

        try:
            url = self.text1.get()
            p = requests.get(url)
            out = open(self.text2.get(), "wb")
            out.write(p.content)
            out.close()
            self.textButton1.set("Сделано")
            self.Button1.configure(background="green")
        except PermissionError:
            self.textButton1.set("ERROR name file")
            self.Button1.configure(background="red")

        except requests.exceptions.InvalidSchema:
            self.textButton1.set("InvalidShema")
            self.Button1.configure(background="red")

        except requests.exceptions.ConnectionError:
            self.textButton1.set("ConnectionError")
            self.Button1.configure(background="red")


if __name__ == "__main__":
    vp_start_gui()

